theme: jekyll-theme-minimal
title: PARAMOR
description: Platform and Resource for Atomic, Molecular and Optical Research
url: about
show_downloads: False
navigation:
  - title: About
    url: about
  - title: Setup
    url: setup
